[package]
name = "rust_rest"
version = "0.1.0"
authors = ["Michael Kernaghan <michaelkernaghan@ecadlabs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = { version = "2.6.2", features = ["json"] }